### ISSUE TITLE
Converting Adafruit_NAU7802 Digital Output to Value with Units

### ISSUE THREAD

**Issue by jguarino211** [adafruit/Adafruit_NAU7802#16]
Hello All,

I am using the Adafruit_NAU7802 library to read values from an S-Beam load cell using an Arduino. The serial monitor displays ta digital value "Read 1544" for example. If a compressive load is applied to the load cell, sure the value increases, but the value is unitless. How can I pull the calibration factor and zero offset from the code and use them to convert what I think is a digital output into a gram, lbf, or N? Any advice would help!

Thanks,
John G

**Comment by caternuson** [comment]
This library only provides a means for getting the raw "unitless" readings from the ADC. The calibration features of the NAU7802 pertain to the ADC - to ensure good raw readings. Calibration for computing engineering units from the raw ADC readings is a procedure that would be done for your specific setup. See here for a basic overview:
https://learn.adafruit.com/calibrating-sensors/why-calibrate

Closing since this is not a library issue.
